AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for Rust on AWS Lambda

Resources:
  RustFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      CodeUri: ../lambda
      Architectures:
        - x86_64

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ../lambda
      DockerTag: rustv1

Outputs:
  FunctionName:
    Description: Lambda function name
    Value: !Ref RustFunction
